apiVersion: apps/v1
kind: Deployment
metadata:
  name: share
  labels:
    app: share
spec:
  replicas: 2
  selector:
    matchLabels:
      app: share
  containers:
    - name: share
      image: stanographer/upwordly
      ports:
        - containerPort: 9999
