version: '3'
services:
  reverseproxy:
    image: reverseproxy
    ports:
      - '80:9000'
      - '443:9000'
    restart: always
  server:
    container_name: upwordly
    restart: always
    build:
      context: ./
    command: npm start
    volumes:
      - /usr/app
      - /usr/app/node_modules
    ports:
      - '9000:9000'
    links:
      - mongo
      - redis
    environment:
      - NODE_ENV=production
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - '6379:6379'
  nginx:
    image_name: client
    image: nginx:alpine
    depends_on:
      - reverseproxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
