version: '3'
services:
  server:
    container_name: upwordly
    restart: always
    build:
      context: ./server/
    command: /usr/app/node_modules/.bin/nodemon app.js
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - '1988:1988'
      - '9090:9090'
    links:
      - mongo
      - redis
    environment:
      - NODE_ENV=production
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - '6379:6379'
  client:
    build:
      context: ./client/
    command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - '3000:3000'
