version: '3'
services:
  app:
    container_name: upwordly
    restart: always
    build: .
    ports:
      - '80:1988'
      - '9090:9090'
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - '6379:6379'
