version: '3.4'

services:
  app:
    build: .
    restart: always
    links:
      - mongo
      - redis
    ports:
      - 9999:9999
  frontend:
    build: frontend
    restart: always
    ports:
    - 3000:3333
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
