version: '3'
services:
  server:
    container_name: upwordly
    restart: always
    build: .
    command: npm start
    ports:
      - '9000:9000'
    links:
      - mongo
      - redis
    environment:
      - NODE_ENV=production
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - '6379:6379'
  client:
    build:
      context: ./client/
    environment:
      - REACT_APP_ENV=production
    command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    env_file: ./client/.env
    ports:
      - '3000:3000'
